### PR TITLE
Frontend theme layout updates

### PR DESCRIPTION
**Pull request by achen2401**
- introduce uw color theme (purple and gold) to the app (ok?) (NOTE: **not** using it yet, but can use if we need).
- minor layout adjustments, i.e. spacing, padding and margin to summary page.

### CODE REVIEW

**Comment by mcjustin** [comment]
@achen2401  can you please attach a screenshot? This is a WA state project, so we don't want to get too UW-centric

**Comment by achen2401** [comment]
Ah, got it! UW theme variables can be removed let me know if they should be.
Here is the screenshot:
opioidTheme

**Comment by achen2401** [comment]
Just noting here that I **removed** uw-specific theme styling changes.  But the screenshot is just to show how it looks like it we do use uw-specific theme colors.

**Comment by ivan-c** [comment]
Looks good but am seeing different colors
image

**Comment by ivan-c** [comment]
I've set up Netlify Deploy Previews. the below launch URL should launch the version in this PR

[SoF Launch](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-3--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&fhir_ver=4)

**Comment by ivan-c** [comment]
> I've set up Netlify Deploy Previews. the below launch URL should launch the version in this PR
> 
> [SoF Launch](https://launch.smarthealthit.org/launcher?launch_uri=https%3A%2F%2Fdeploy-preview-3--distracted-jepsen-bc9c39.netlify.com%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&fhir_ver=4)

NB: This Launch URL may not work if the SMART Health IT Sandbox has been reset (and our test patient Brenda Jackson). Look for response code `410 gone` to know definitively

**Pull request merged**
